var agenda = [
    {
        "nombre":"Salva",
        "telefono":12345,
        "email":[
            "salva@correo.com",
            "otroemail@otro.es",
            "unomas@email.com"
        ]
    },
    {
        "nombre":"Salva",
        "telefono":12345,
        "email":[
            "salva@correo.com",
            "otroemail@otro.es",
            "unomas@email.com"
        ]
    }
]
console.log(agenda)